name: Sync to Gold

on:
  workflow_dispatch:

jobs:
  sync-to-gold:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: malaktolba
          repositories: gold

      - name: Clone gold repo and create update-readme branch
        run: |
          git config --global user.name "Auto Bot"
          git config --global user.email "bot@example.com"
          git clone https://x-access-token:${{ steps.generate_token.outputs.token }}@github.com/malaktolba/gold.git gold
          cd gold
          git fetch origin main
          git branch -D update-readme || true
          git checkout -b update-readme origin/main
          echo "Automated update on $(date)" >> README.md
          git add README.md
          git commit -m "Automated README update"
          git push origin update-readme
        env:
          GIT_TERMINAL_PROMPT: 0

      - name: Create Pull Request
        run: |
          cd gold
          gh pr create \
            --repo malaktolba/gold \
            --base main \
            --head update-readme \
            --title "Automated README Update" \
            --body "This PR was created by GitHub Actions."
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}

      - name: Auto-merge PR
        run: |
          PR_NUMBER=$(gh pr list --repo malaktolba/gold --head update-readme --json number --jq '.[0].number')
          gh pr merge $PR_NUMBER \
            --repo malaktolba/gold \
            --merge \
            --admin
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
