name: Sync to Gold
on:
 workflow_dispatch:
jobs:
 sync:
   runs-on: self-hosted
   steps:
     - name: Generate GitHub App token
       uses: actions/create-github-app-token@v1
       with:
         app_id: ${{ secrets.APP_ID }}
         private_key: ${{ secrets.PRIVATE_KEY }}
 update-gold:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Clone gold repo
        run: |
            git config --global user.name "Auto Bot"
            git config --global user.email "bot@example.com"
            git clone https://x-access-token:${{ secrets.GOLD_PAT }}@github.com/malaktolba/gold.git
        env:
            GIT_TERMINAL_PROMPT: 0


      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GOLD_PAT }}
          repository: <owner>/gold
          title: "Automated README Update"
          body: "This PR was created by a GitHub Actions workflow."
          base: master
          head: update-readme

      - name: Auto-merge PR
        run: |
          gh pr merge update-readme --repo <owner>/gold --merge --admin
        env:
          GH_TOKEN: ${{ secrets.GOLD_PAT }}
