name: My first workflow
on:
 workflow_dispatch:
jobs:
 job1:
   runs-on: self-hosted
   steps:
     - name: Get GitHub App Token
       uses: actions/create-github-app-token@v1
       id: token
       with:
         app_id: ${{ vars.GITHUB_APP_ID }}
         private_key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}
     - name: Checkout repo
       uses: actions/checkout@v4
       with:
         repository: malaktolba/gold
         token: ${{ steps.token.outputs.token }}
         ref: master
     - name: Change something
       run: echo "hello from workflow" >> log.txt
     - name: Create Pull Request
       id: cpr
       uses: peter-evans/create-pull-request@v6
       with:
         token: ${{ steps.token.outputs.token }}
         commit-message: "added log.txt from workflow"
         branch: malak
         base: master
         title: "Beginner test PR"
         body: "This pull request was made by my workflow."
     - name: Merge Pull Request
       uses: peter-evans/merge-pull-request@v3
       with:
         token: ${{ steps.token.outputs.token }}
         pull-request: ${{ steps.cpr.outputs.pull-request-number }}
         merge-method: squash
